#!/usr/bin/env bash
# script that Creates the file /var/run/myscript.pid containing its PID
# Displays To infinitely and beyond indefinitely
# Displays I hate the kill command when a receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself while receiving a SIGQUIT or SIGTERM signal
terminator(){
       rm/var/run/myscript.pid
       exit
}
echo "$$" > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	trap 'echo "I hate the kill command" or terminator' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'terminator' SIGQUIT
done

