#!/usr/bin/env bash
# script that displays To infinty and beyond indefinitey with sleep 2 and Iam invincible!!! with a SIGTERM signal
while true 
do 
         echo "To beyond and beyond"
         sleep 2
         trap 'echo "I am invincible!!!"' SIGTERM
done
